skid_steer_drive_controller:
  type: "skid_steer_controller/SkidSteerController"
  left_wheel: ['left_front_wheel_joint', 'left_rear_wheel_joint']
  right_wheel: ['right_front_wheel_joint', 'right_rear_wheel_joint']
  publish_rate: 50
  wheel_separation: 0.50
  wheel_radius: 0.067
  base_frame_id: base_link
  odom_frame_id: odom
  enable_odom_tf: true
  estimate_velocity_from_position: true
  linear:
    x:
      has_velocity_limits: true
      max_velocity: 0.09
      has_acceleration_limits: true
      max_acceleration: 3.0
  angular:
    z:
      has_velocity_limits: true
      max_velocity: 0.45
      has_acceleration_limits: true
      max_acceleration: 6.0

/robot_gui_bridge:
  pid_gains:
    left_front_wheel_joint: {p: 20.0, i: 0.01, d: 0.0, i_clamp: 0.0}
    left_rear_wheel_joint: {p: 20.0, i: 0.01, d: 0.0, i_clamp: 0.0}
    right_front_wheel_joint: {p: 20.0, i: 0.01, d: 0.0, i_clamp: 0.0}
    right_rear_wheel_joint: {p: 20.0, i: 0.01, d: 0.0, i_clamp: 0.0}
